# Generated by Django 5.2.6 on 2025-09-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=6, unique=True)),
                ("description", models.TextField()),
                ("polygon", models.JSONField(blank=True, null=True)),
                ("floorplan_available", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=10, unique=True)),
                ("floor", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=100)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="class_locator.block",
                    ),
                ),
            ],
        ),
    ]
